Repository djunicode/masters-information-portal, pull requests merged in 2020-03, with the labels that each got.

#16 Update User schema and routes
  app.js
  controllers/user.js
  infra/encryption/index.js
  infra/jwt/index.js
  models/user.js
  package.json
Labels: backend

#25 #2 chat model and private chat revamp
  controllers/chat.js
  controllers/index.js
  infra/WebSockets/index.js
  models/chat.js
  models/index.js
Labels: backend

#26 Add testing and change tags
  app.js
  config/logger.js
  controllers/forum.js
  controllers/tag.js
  index.js
  models/tag.js
  package.json
  test/config.js
  test/tag.js
Labels: backend

#20 Add Forum, Chat and Update Login Component Design
  webapp/README.md
  webapp/package.json
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/manifest.json
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/Components/MainMessenger/Compose/Compose.css
  webapp/src/Components/MainMessenger/Compose/index.js
  webapp/src/Components/MainMessenger/ConversationList/ConversationList.css
  webapp/src/Components/MainMessenger/ConversationList/index.js
  webapp/src/Components/MainMessenger/List/List.css
  webapp/src/Components/MainMessenger/List/List.js
  webapp/src/Components/MainMessenger/List/Profile.png
  webapp/src/Components/MainMessenger/MessageList/MessageList.css
  webapp/src/Components/MainMessenger/MessageList/index.js
  webapp/src/Components/MainMessenger/Messenger/Messenger.css
  webapp/src/Components/MainMessenger/Messenger/index.js
  webapp/src/Components/forum.js
  webapp/src/Components/login.js
  webapp/src/Components/loginLogo.js
  webapp/src/Components/navbar.js
  webapp/src/Components/register.js
  webapp/src/Components/router.js
Labels: frontend

#39 Refractor Backend
  .env.development
  .gitignore
  app.js
  config/constants.js
  config/db.js
  config/logger.js
  config/middlewares.js
  controllers/chat.js
  controllers/forum.js
  controllers/tag.js
  controllers/user.js
  index.js
  infra/.DS_Store
  infra/WebSockets/index.js
  infra/encryption.js
  infra/encryption/index.js
  infra/jwt.js
  infra/jwt/index.js
  infra/middleware/auth.js
  infra/webSockets.js
  middleware/auth.js
  models/chat.js
  models/forum.js
  models/index.js
  models/tag.js
  models/user.js
  package.json
  routes/chat.js
  routes/forum.js
  routes/index.js
  routes/tag.js
  routes/user.js
  webapp/.gitignore
  yarn.lock
Labels: backend

#43 Added tag and user tests
  .eslintrc.json
  .gitignore
  .prettierrc
  app.js
  controllers/user.js
  middleware/auth.js
  models/user.js
  test/config.js
  test/tag.js
  test/user_after_login.js
  test/user_register_login.js
Labels: backend

#38 Add Edit Profile Component
  .gitignore
  webapp/package.json
  webapp/src/App.css
  webapp/src/Components/editProfile.js
  webapp/src/Components/navbar.js
  webapp/src/Components/register.js
  webapp/src/Components/router.js
Labels: frontend

#44 Added refresh token support and fixed auth middleware
  .env.development
  config/constants.js
  controllers/user.js
  infra/jwt.js
  middleware/auth.js
  models/user.js
  routes/user.js
Labels: backend

#47 Add Supporting Libraries: build.sh #22
  app.js
  build.sh
  models/forum.js
  package.json
Labels: backend

#48 Serve frontend only in production
  app.js
Labels: backend

#46 Chat API test and SocketIO changes
  infra/webSockets.js
  middleware/auth.js
  models/user.js
  routes/chat.js
Labels: backend

#29 Add forum routes authentication
  app.js
  controllers/forum.js
  middleware/auth.js
  middleware/forumAuth.js
  package.json
  routes/forum.js
  webapp/.gitignore
Labels: backend

#53 Backend
  controllers/user.js
  middleware/auth.js
  middleware/multer.js
  models/user.js
  package.json
  routes/user.js
Labels: backend

#51 Add upvote,downvote,pin routes for Forum, Add respective tests
  controllers/forum.js
  middleware/auth.js
  models/forum.js
  routes/forum.js
  test/config.js
  test/forum.js
  test/user_after_login.js
  test/user_register_login.js
Labels: backend

#61 Add filtering of forum posts #22
  controllers/forum.js
Labels: backend

#58 Revamp Forum Model
  controllers/forum.js
  middleware/forumAuth.js
  models/forum.js
  test/config.js
  test/forum.js
  test/user_after_login.js
Labels: backend

#60 User role addition and auth
  controllers/user.js
  middleware/auth.js
  models/user.js
  routes/user.js
Labels: backend

#64 Integrate EditProfile, Login and Signup
  .env.development
  .eslintrc.json
  .gitignore
  .prettierrc
  app.js
  build.sh
  config/constants.js
  controllers/forum.js
  controllers/user.js
  infra/.DS_Store
  infra/jwt.js
  infra/webSockets.js
  middleware/auth.js
  middleware/forumAuth.js
  middleware/multer.js
  models/forum.js
  models/user.js
  package.json
  routes/chat.js
  routes/forum.js
  routes/user.js
  test/config.js
  test/forum.js
  test/tag.js
  test/user_after_login.js
  test/user_register_login.js
  webapp/.gitignore
  webapp/README.md
  webapp/package.json
  webapp/src/App.js
  webapp/src/Components/editProfile.js
  webapp/src/Components/login.js
  webapp/src/Components/navbar.js
  webapp/src/Components/register.js
  webapp/src/Components/router.js
  webapp/src/Components/tagRequests.js
Labels: integration

#52 Chat fixed
  webapp/package.json
  webapp/src/Components/MainMessenger/Compose/Compose.css
  webapp/src/Components/MainMessenger/Compose/index.js
  webapp/src/Components/MainMessenger/ConversationList/ConversationList.css
  webapp/src/Components/MainMessenger/ConversationList/index.js
  webapp/src/Components/MainMessenger/List/List.css
  webapp/src/Components/MainMessenger/List/List.js
  webapp/src/Components/MainMessenger/MessageList/MessageList.css
  webapp/src/Components/MainMessenger/MessageList/index.js
  webapp/src/Components/MainMessenger/Messenger/Messenger.css
  webapp/src/Components/MainMessenger/Messenger/index.js
  webapp/src/Components/Messages.js
  webapp/src/Components/Profile.png
  webapp/src/Components/navbar.js
  webapp/src/Components/router.js
Labels: frontend

#67 Add Profile Component
  routes/user.js
  webapp/package.json
  webapp/src/Components/editProfile.js
  webapp/src/Components/mystyles.css
  webapp/src/Components/profilephoto.jpg
  webapp/src/Components/profpage3.js
  webapp/src/Components/router.js
Labels: frontend

#66 Readability enhancing code
  constants/roles.js
  middleware/auth.js
  routes/user.js
Labels: backend

#65 Added support for following and unfollowing tags
  controllers/tag.js
  controllers/user.js
  models/tag.js
  models/user.js
  routes/tag.js
Labels: backend

#68 Disable Tag Creation in Sign-up and Edit Profile
  models/user.js
  webapp/src/App.js
  webapp/src/Components/editProfile.js
  webapp/src/Components/login.js
  webapp/src/Components/navbar.js
  webapp/src/Components/register.js
  webapp/src/Components/tagRequests.js
Labels: frontend

#71 Cleanliness enhanced
  constants/roles.js
  routes/user.js
Labels: backend

#63 Add update route for Tags and fix problem with Tag slugs
  controllers/tag.js
  models/tag.js
  routes/tag.js
Labels: backend

#72 Add {new:true} for all PUT/ routes #69
  controllers/forum.js
  controllers/tag.js
Labels: backend
