Repository djunicode/masters-information-portal, pull requests merged in 2020-05, with the labels that each got.

#86 Add helper file
  webapp/src/Components/editProfile.js
  webapp/src/Components/register.js
  webapp/src/Components/tagRequests.js
  webapp/src/Helpers/fetchRequests.js
Labels: frontend

#90 Changes in backend for heroku deployment
  .env.development
  .gitignore
  app.js
  config/morganConfig.js
  controllers/forum.js
  heroku-deployment.md
  index.js
  infra/webSockets.js
  jsdoc.json
  package.json
Labels: backend

#88 Update Side Navigation Bar
  config/constants.js
  routes/user.js
  webapp/src/App.js
  webapp/src/Components/editProfile.js
  webapp/src/Components/login.js
  webapp/src/Components/navbar.js
  webapp/src/Components/register.js
  webapp/src/Helpers/fetchRequests.js
Labels: frontend

#94 Created Add-Resource Page and made mobile view compatible, added route and fixed loggedIn issues
  webapp/src/Components/AddResources.js
  webapp/src/Components/Messages.js
  webapp/src/Components/router.js
Labels: frontend

#93 Improve File Structure, Add loginCheck.js & Clean-up code
  webapp/src/App.js
  webapp/src/Components/Navbar/navbar.js
  webapp/src/Components/Router/router.js
  webapp/src/Components/router.js
  webapp/src/Helpers/checkLogin.js
  webapp/src/Pages/Edit Profile/editProfile.js
  webapp/src/Pages/Login and Sign-up/login.js
  webapp/src/Pages/Login and Sign-up/register.js
  webapp/src/assets/images/profile-icon.png
  webapp/src/assets/svg/loginLogo.js
Labels: frontend

#91 Update test Config and setup CI with github actions
  .github/workflows/main.yml
  config/constants.js
  package-lock.json
  package.json
  routes/user.js
  test/config.js
  test/forum.js
  test/tag.js
  test/user_after_login.js
  test/user_register_login.js
  webapp/package-lock.json
Labels: backend

#96 Add:Notification model #95
  models/chat.js
  models/index.js
  models/notification.js
Labels: backend

#98 Added Search Profile page, University Page and Updated Profile Page
  webapp/src/Components/Router/router.js
  webapp/src/Components/mystyles.css
  webapp/src/Components/profile3.js
  webapp/src/Components/profpage3.js
  webapp/src/Components/universitypage.js
Labels: frontend

#99 Add Homepage
  webapp/src/App.js
  webapp/src/Components/Router/router.js
  webapp/src/Pages/Homepage/home.js
  webapp/src/Pages/Homepage/homepage.css
  webapp/src/Pages/Login and Sign-up/login.js
  webapp/src/Pages/Login and Sign-up/register.js
  webapp/src/assets/images/image1.png
  webapp/src/assets/images/image2.png
  webapp/src/assets/images/image3.png
  webapp/src/assets/images/image4.png
  webapp/src/assets/images/image5.png
  webapp/src/assets/svg/HeaderImg.svg
  webapp/src/assets/svg/Homepage_header.svg
  webapp/src/assets/svg/loginLogo.js
  webapp/src/assets/svg/loginLogo.svg
Labels: frontend

#101 Development
  webapp/src/Components/forum.js
  webapp/src/Components/resources.js
Labels: frontend

#100 Add Notification creating functions
  .eslintignore
  config/constants.js
  config/db.js
  config/logger.js
  config/middlewares.js
  config/morganConfig.js
  constants/notifications.js
  constants/roles.js
  controllers/chat.js
  controllers/tag.js
  infra/encryption.js
  infra/jwt.js
  infra/notifications.js
  infra/webSockets.js
  middleware/auth.js
  middleware/forumAuth.js
  middleware/multer.js
  models/forum.js
  models/index.js
  models/notification.js
  models/tag.js
  package-lock.json
  package.json
  routes/chat.js
  routes/tag.js
  webapp/.eslintignore
  webapp/package-lock.json
  webapp/package.json
Labels: backend

#102 Added Question Reply
  webapp/src/Components/Messages.js
  webapp/src/Components/Navbar/navbar.js
  webapp/src/Components/QuestionReply.js
  webapp/src/Components/Router/router.js
Labels: frontend

#103 Add notification routes
  app.js
  controllers/forum.js
  controllers/notifications.js
  infra/webSockets.js
  routes/index.js
  routes/notifications.js
Labels: backend

#104 Misc Improvements
  webapp/src/Components/Navbar/navbar.js
  webapp/src/Components/Router/router.js
  webapp/src/Pages/Edit Profile/editProfile.js
  webapp/src/Pages/Homepage/home.js
  webapp/src/Pages/Homepage/homepage.css
  webapp/src/Pages/Login and Sign-up/register.js
Labels: frontend

#108 Chat route updated changes
  controllers/chat.js
Labels: backend

#109 Improvements & Bug Fixes
  webapp/src/Components/Navbar/navbar.js
  webapp/src/Helpers/validateForm.js
  webapp/src/Pages/Edit Profile/editProfile.js
  webapp/src/Pages/Login and Sign-up/register.js
Labels: frontend

#112 Code changes made to facilitate frontend application
  infra/webSockets.js
  models/chat.js
Labels: integration

#111 Improve App Performance
  webapp/src/App.js
  webapp/src/Components/Navbar/navbar.js
  webapp/src/Helpers/fetchRequests.js
  webapp/src/Helpers/validateForm.js
  webapp/src/Pages/Edit Profile/editProfile.js
  webapp/src/Pages/Login and Sign-up/login.js
  webapp/src/Pages/Login and Sign-up/register.js
Labels: frontend

#114 fix upvote downvote logic
  controllers/forum.js
  models/forum.js
Labels: backend
